# Generated by Django 5.1.5 on 2025-03-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendor.vendor"
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribues",
                to="product.variation",
            ),
        ),
    ]
