# Generated by Django 5.1.5 on 2025-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_info',
            field=models.CharField(max_length=100),
        ),
    ]
